# test_kappa_sweep.R
#
# R-side companion to test_kappa_sweep.m.  Reads each per-kappa CSV
# generated by the MATLAB script and runs both R methods through the
# same iterative-acceptance framework:
#
#   - circular::lm.circular: chi-squared LRT, accept if p < .05
#   - brms von_mises mixed:  LOO comparison, accept if elpd_diff > 2*se_diff
#
# Also reports the block (order 0 vs order 3) detection statistic for
# each method as a sanity check on whether the cubic effect is even
# recoverable in principle at that kappa.
#
# brms refits each (kappa, order) combo (data changes each kappa, so the
# file= cache only helps if you re-run the script).  Total runtime on a
# laptop is ~30-60 minutes the first time through.

suppressPackageStartupMessages({
  library(circular)
  library(brms)
  library(loo)
  library(readr)
})
options(mc.cores = parallel::detectCores())

OUT <- "R_outputs_kappa"
dir.create(OUT, showWarnings = FALSE, recursive = TRUE)

kappa_list <- c(4, 10, 20, 50, 100)
orders     <- 0:4

priors <- c(
  prior(normal(0, 1),         class = "Intercept"),
  prior(normal(0, 1),         class = "b"),
  prior(student_t(3, 0, 2.5), class = "sd"),
  prior(gamma(2, 0.5),        class = "kappa")
)

build_X_at_order <- function(k, dat) {
  if (k == 0) {
    X <- model.matrix(~ electrode + sex, data = dat)
  } else {
    poly_terms <- sprintf("I(Agez^%d)", 1:k)
    intx_terms <- sprintf("I(Agez^%d):electrode", 1:k)
    rhs <- paste(c(poly_terms, "electrode", "sex", intx_terms), collapse = " + ")
    X <- model.matrix(as.formula(paste("~", rhs)), data = dat)
  }
  X[, -1, drop = FALSE]
}

build_brms_formula <- function(k) {
  if (k == 0) {
    as.formula("phase_pref ~ electrode + sex + (1 | Subj_ID)")
  } else {
    as.formula(sprintf("phase_pref ~ poly(Agez, %d, raw = TRUE) * electrode + sex + (1 | Subj_ID)", k))
  }
}

iter_lrt <- function(LL, npar) {
  sel <- 0
  for (k in 2:length(LL)) {
    chi2 <- 2 * (LL[k] - LL[k-1])
    df   <- npar[k] - npar[k-1]
    p    <- pchisq(max(chi2, 0), df, lower.tail = FALSE)
    if (!is.na(p) && p < 0.05) sel <- k - 1 else break
  }
  sel
}

iter_loo <- function(loos) {
  sel <- 0
  for (k in 2:length(loos)) {
    cmp    <- loo_compare(loos[[k-1]], loos[[k]])
    e1     <- loos[[k-1]]$estimates["elpd_loo","Estimate"]
    e2     <- loos[[k]]$estimates["elpd_loo","Estimate"]
    e_diff <- e2 - e1
    e_se   <- abs(cmp[2, "se_diff"])
    if (e_diff > 2 * e_se) sel <- k - 1 else break
  }
  sel
}

results <- data.frame()

for (kappa_true in kappa_list) {
  cat(sprintf("\n========================================================\n"))
  cat(sprintf("  kappa = %g\n", kappa_true))
  cat(sprintf("========================================================\n"))

  csv <- sprintf("test_kappa_sweep_K%g.csv", kappa_true)
  d <- read_csv(csv, show_col_types = FALSE)
  d$Subj_ID   <- factor(d$Subj_ID)
  d$electrode <- as.numeric(d$electrode)
  d$sex       <- as.numeric(d$sex)
  age_mean <- mean(d$Age); age_sd <- sd(d$Age)
  d$Agez   <- (d$Age - age_mean) / age_sd
  d$phase_pref <- ((d$phase_pref + pi) %% (2*pi)) - pi
  d$phase_circ <- circular(d$phase_pref, units = "radians",
                           modulo = "2pi", template = "none")

  # ---- circular::lm.circular at each order ----
  LL_lc <- numeric(length(orders))
  np_lc <- numeric(length(orders))
  for (i in seq_along(orders)) {
    k <- orders[i]
    X <- build_X_at_order(k, d)
    fit <- tryCatch(lm.circular(y = d$phase_circ, x = X, type = "c-l",
                                init = rep(0, ncol(X)), verbose = FALSE),
                    error = function(e) NULL)
    if (is.null(fit)) { LL_lc[i] <- NA; np_lc[i] <- NA; next }
    eta <- as.numeric(cbind(1, X) %*% c(fit$mu, fit$coefficients))
    r   <- ((d$phase_pref - eta + pi) %% (2*pi)) - pi
    LL_lc[i] <- -length(r) * log(2*pi*besselI(fit$kappa, 0)) +
                 fit$kappa * sum(cos(r))
    np_lc[i] <- ncol(X) + 1
  }
  sel_lc <- iter_lrt(LL_lc, np_lc)

  # block 0 vs 3
  chi2_b <- 2 * (LL_lc[4] - LL_lc[1])
  df_b   <- np_lc[4] - np_lc[1]
  p_block_lc <- pchisq(max(chi2_b, 0), df_b, lower.tail = FALSE)

  cat(sprintf("  lm.circular: iter LRT -> %d, block(0 vs 3) p = %.4g\n",
              sel_lc, p_block_lc))

  # ---- brms at each order ----
  fits <- list(); loos <- list()
  for (i in seq_along(orders)) {
    k <- orders[i]
    cat(sprintf("  brms order %d... ", k))
    fits[[i]] <- brm(
      formula = build_brms_formula(k),
      data    = d,
      family  = von_mises(link = "tan_half", link_kappa = "log"),
      prior   = priors,
      chains  = 4, iter = 3000, warmup = 1000,
      control = list(adapt_delta = 0.95),
      seed    = 1, refresh = 0,
      file    = file.path(OUT, sprintf("brms_K%g_order%d.rds", kappa_true, k)),
      file_refit = "on_change",
      silent  = 2
    )
    loos[[i]] <- loo(fits[[i]])
    cat(sprintf("elpd_loo = %.2f\n", loos[[i]]$estimates["elpd_loo","Estimate"]))
  }
  sel_brms <- iter_loo(loos)

  cmp_b <- loo_compare(loos[[1]], loos[[4]])
  e1 <- loos[[1]]$estimates["elpd_loo","Estimate"]
  e4 <- loos[[4]]$estimates["elpd_loo","Estimate"]
  block_brms_diff <- e4 - e1
  block_brms_se   <- abs(cmp_b[2, "se_diff"])
  block_brms_z    <- block_brms_diff / max(block_brms_se, 1e-9)

  cat(sprintf("  brms       : iter LOO -> %d, block(0 vs 3) elpd_diff = %.2f, se = %.2f, z = %.2f\n",
              sel_brms, block_brms_diff, block_brms_se, block_brms_z))

  results <- rbind(results, data.frame(
    kappa            = kappa_true,
    sel_lm_circular  = sel_lc,
    sel_brms_loo     = sel_brms,
    p_block_lc       = p_block_lc,
    block_brms_z     = block_brms_z,
    block_brms_diff  = block_brms_diff,
    block_brms_se    = block_brms_se
  ))
}

cat("\n========================================================\n")
cat("  R-side kappa sweep summary (truth = 3, N = 300)\n")
cat("========================================================\n")
print(results, digits = 4, row.names = FALSE)

write.csv(results, file.path(OUT, "kappa_sweep_R_results.csv"), row.names = FALSE)
cat(sprintf("\nWritten to %s\n", file.path(OUT, "kappa_sweep_R_results.csv")))
